#!/usr/bin/env bash

show_help(){
cat <<EOF
Argument: <nil>

Output   :   usa_pct% wait_pct% sys_pct% usr_pct%
Example  :   0.4 0.2 0 0
EOF
exit 0;
}
[ "$1" == "help" -o "$1" == "h" ] && show_help;

check(){

  if [ ! -x "/usr/bin/vmstat" ]; then
	return
  fi

  local cpu_usage=
  cpu_usage=( $( ( /usr/bin/vmstat 1 10 |\
		   /bin/awk '($1!~/[0-9]+/ || NF!=17){next;} \
				{id+=$15;wa+=$16;sy+=$14;us+=$13} \
				END{print 100-id/10,wa/10,sy/10,us/10}'
		 ) 2>/dev/null )
 	    )

  echo "${cpu_usage[*]}"
}

check
