#!/usr/bin/env bash

show_help(){
cat <<EOF
Arguments:    {urls}
Usage:   http://127.0.0.1:80/index.php  https://mail.eyou.net:443/a.html

Output:   
{url} succ
{url} warn http_code

Example:
http://127.0.0.1:80/index.php succ
https://mail.eyou.net:443/a.html warn 400
EOF
exit 0;
}
[ "$1" == "help" -o "$1" == "h" ] && show_help;

urls=$*
time_out=5

check(){
  if [ -f "/usr/bin/curl" ] && [ -x "/usr/bin/curl" ]; then
	:
  else
        return
  fi

  if [ -z "${urls}" ]; then
        return
  fi

  for url in `echo "${urls}"`;
  do
	prot=$(echo "${url}" | awk -F: '{print $1}')

	if [ "${prot}" == "https" ]; then
		code=$(/usr/bin/curl -k \
				--location --max-redirs 3 \
				--max-time ${time_out} -s -o /dev/null \
				-w "%{http_code}" \
				"${url}" 2>/dev/null)
	elif [ "${prot}" == "http" ]; then
		code=$(/usr/bin/curl \
				--location --max-redirs 3 \
				--max-time ${time_out} -s -o /dev/null \
				-w "%{http_code}" \
				"${url}" 2>/dev/null)
	else
		continue
	fi

	if [ "$code" == "200" ]; then
		echo "${url} succ"
	else
		echo "${url} warn ${code}"
	fi
  done
}

check
