#!/usr/bin/env bash

show_help(){
cat <<EOF
Arguments:   {mysqladmin_path}  {ip,port,user,pass  ip,port,user,pass  ...}
Arguments:   {mysqladmin_path}  {unixsock1,user,pass  unixsock2,user,pass  ...}
Usage:       /usr/local/eyou/mail/opt/mysql/bin/mysqladmin "/usr/local/eyou/mail/run/em_mysql.sock,eyou,eyou 127.0.0.1,3316,eyou,eyou"

Output:   
{ip:port} succ
{ip:port} warn {[result]}
Example:
127.0.0.1:3308 warn 'Access denied for user 'eyou'@'localhost' (using password: YES)'
127.0.0.1:3308 succ
EOF
exit 0;
}
MODE=0
[ "$1" == "help" -o "$1" == "h" ] && show_help;

mysqladmin_path="$1"
mysql_conn_conf="$2"
mysql_time_out=10

[ -z "${mysqladmin_path}" ] && exit 0 # mysqladmin_path="/usr/local/eyou/mail/opt/mysql/bin/mysqladmin"
[ -z "${mysql_conn_conf}" ] && exit 0 # mysql_conn_conf="127.0.0.1,3306,eyou,eyou"

check() {

  if [ -f "${mysqladmin_path}" ] && [ -x "${mysqladmin_path}" ]; then
	:
  else
	return
  fi

  for pairs in `echo "${mysql_conn_conf}"`
  do
	sepnum=$(echo -e "${pairs}" | /bin/awk -F"," 'END{print --NF}')

  	if [ "${sepnum}" == "3" ]; then
  		mysql_host="$(echo -e "${pairs}"|/bin/awk -F"," '{print $1}')"
  		mysql_port="$(echo -e "${pairs}"|/bin/awk -F"," '{print $2}')"
  		mysql_user="$(echo -e "${pairs}"|/bin/awk -F"," '{print $3}')"
  		mysql_pass="$(echo -e "${pairs}"|/bin/awk -F"," '{print $4}')"
		mysql_addr="${mysql_host}:${mysql_port}"
        	cmd="${mysqladmin_path} -h ${mysql_host} -P ${mysql_port} -u${mysql_user} --connect-timeout ${mysql_time_out} "
  	elif [ "${sepnum}" == "2" ]; then
  		unixsocket="$(echo -e "${pairs}"|/bin/awk -F"," '{print $1}')"
  		mysql_user="$(echo -e "${pairs}"|/bin/awk -F"," '{print $2}')"
  		mysql_pass="$(echo -e "${pairs}"|/bin/awk -F"," '{print $3}')"
		mysql_addr="${unixsocket}"
        	cmd="${mysqladmin_path} -S ${unixsocket} -u${mysql_user} --connect-timeout ${mysql_time_out} "
  	else
        	return
  	fi
  	if [ -n "${mysql_pass}" ]; then
        	cmd="${cmd} -p${mysql_pass} "
  	fi


	ping_result=$( ${cmd} ping 2>&1 )
	ping_result=$( (echo -e "${ping_result}" | sed -e '/password on the command line/d' |tr -d '\r\n') 2>&- )
	if [ "$(echo "${ping_result}"|grep -E -o -i "is alive")" == "" ]; then
		echo "${mysql_addr} warn ${ping_result}"
	else
		echo "${mysql_addr} succ"
	fi
  done
}

check
